"""Initial schema

Revision ID: bc0d679af70e
Revises: 
Create Date: 2025-10-22 20:36:47.884663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision = 'bc0d679af70e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('first_name', sa.String(length=100), nullable=False, comment="User's first name"),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment="User's last name"),
    sa.Column('company_name', sa.String(length=255), nullable=True, comment='Company or organization name'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='User location'),
    sa.Column('sector', sa.String(length=100), nullable=True, comment='Industry sector (Municipal, Industrial, Commercial, Residential)'),
    sa.Column('subsector', sa.String(length=100), nullable=True, comment='Industry subsector'),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('client', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False, comment='Municipal, Industrial, Commercial, Residential'),
    sa.Column('subsector', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('project_type', sa.String(length=100), nullable=True, comment='Type of treatment system'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True, comment='Estimated budget in USD'),
    sa.Column('schedule_summary', sa.String(length=255), nullable=True, comment='High-level schedule summary'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Project status matching frontend enum'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='Completion percentage 0-100'),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Array of tags for categorization'),
    sa.Column('project_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Flexible JSONB storage for all project technical data'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_data_gin', 'projects', ['project_data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=True)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('project_files',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='Storage path (S3 key or local path)'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='File size in bytes'),
    sa.Column('file_type', sa.String(length=20), nullable=True, comment='File extension without dot (pdf, docx, xlsx)'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME type (e.g., application/pdf, application/vnd.openxmlformats-officedocument.wordprocessingml.document)'),
    sa.Column('uploaded_by', sa.UUID(), nullable=True, comment='User who uploaded the file'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='technical, regulatory, financial, other'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('processed_text', sa.Text(), nullable=True, comment='Extracted text content from document'),
    sa.Column('ai_analysis', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='AI analysis results and insights'),
    sa.Column('file_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Additional metadata (page count, dimensions, etc.)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_files_id'), 'project_files', ['id'], unique=True)
    op.create_index(op.f('ix_project_files_project_id'), 'project_files', ['project_id'], unique=False)
    op.create_table('proposals',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False, comment='Proposal version (e.g., v1.0, v2.1)'),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('proposal_type', sa.String(length=50), nullable=False, comment='Conceptual, Technical, or Detailed'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Draft, Current, or Archived'),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('capex', sa.Float(), nullable=True, comment='Capital expenditure estimate in USD'),
    sa.Column('opex', sa.Float(), nullable=True, comment='Annual operational expenditure estimate in USD'),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('technical_approach', sa.Text(), nullable=True),
    sa.Column('implementation_plan', sa.Text(), nullable=True),
    sa.Column('cost_breakdown', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Financial breakdown: equipment_cost, civil_works, installation_piping, etc.'),
    sa.Column('risks', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='List of identified risks'),
    sa.Column('equipment_list', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='List of EquipmentSpec objects with technical details'),
    sa.Column('treatment_efficiency', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Treatment efficiency metrics: COD, BOD, TSS, TN, TP, FOG'),
    sa.Column('operational_costs', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Operational cost breakdown: electrical_energy, chemicals, personnel, maintenance'),
    sa.Column('operational_data', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Operational parameters: required_area_m2, sludge_production, energy_consumption'),
    sa.Column('charts_data', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Chart data for visualization generation'),
    sa.Column('pdf_path', sa.String(length=500), nullable=True, comment='Path to generated PDF file (S3 URL or local path)'),
    sa.Column('ai_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='AI reasoning metadata: usage_stats, proven_cases, deviations, assumptions, confidence_level'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_id'), 'proposals', ['id'], unique=True)
    op.create_index(op.f('ix_proposals_project_id'), 'proposals', ['project_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='Event type: created, updated, status_change, proposal_generated, file_uploaded, etc.'),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=True, comment='User who performed the action'),
    sa.Column('event_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Additional event data (old_value, new_value, etc.)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_event_type'), 'timeline_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_timeline_events_id'), 'timeline_events', ['id'], unique=True)
    op.create_index(op.f('ix_timeline_events_project_id'), 'timeline_events', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_events_project_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_event_type'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_proposals_project_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_project_files_project_id'), table_name='project_files')
    op.drop_index(op.f('ix_project_files_id'), table_name='project_files')
    op.drop_table('project_files')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index('ix_project_data_gin', table_name='projects', postgresql_using='gin')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
